blank_issues_enabled: false
issue_template:
  - name: Bug Report
    description: Report a bug
    title: "[BUG] "
    labels: ["bug"]
    body:
      - type: markdown
        attributes:
          value: |
            Please provide a clear and concise description of the bug.
      - type: textarea
        id: steps-to-reproduce
        attributes:
          label: Steps to Reproduce
          description: List the steps to reproduce the issue.
          placeholder: "1. Go to...\n2. Click on...\n3. See error"
      - type: input
        id: expected-behavior
        attributes:
          label: Expected Behavior
          description: Describe what you expected to happen.
          placeholder: "Expected behavior"
      - type: input
        id: actual-behavior
        attributes:
          label: Actual Behavior
          description: Describe what actually happened.
          placeholder: "Actual behavior"